version: "3.1"
services:
  app:
    build: .
    #image: ivansanchezcom/org-hierarchy
    ports:
      - 3000:3000
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:root@db/orghierarchy
      - PORT=3000
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orghierarchy